name=input("Podaj nazwe pliku z danymi - musi byc w tym samym folderze co program\n")
outname=input("Podaj nazwe pliku wyjsciowego\n")
file=open('{}.txt'.format(name))
TXT=file.read()
file.close()
TXT=TXT.replace("Command: ID\n","")
TXT=TXT.replace("Command:  ID\n","")
TXT=TXT.replace("Specify point:  X = ","")
TXT=TXT.replace("     Y =","")
TXT=TXT.replace("     Z =","")
TXT=TXT.replace("\n"," ")
TXT=TXT.split()
long=len(TXT)
longl=int(long/3)
print(long)
print(longl)
f=open('{}.txt'.format(outname),'a')
f.write("   X         Y       \n Modified file of    DE6-225B-23.3 (2.25 WIDE)    Ameren-M\n           1\n        {:4}\n".format(longl))
f.close()
for i in range(0,long,3):
    f=open('{}.txt'.format(outname),'a')
    f.write("   {:9.6f}   {:9.6f}   {:9.6f}\n".format(float(TXT[i])*0.03937,float(TXT[i+1])*0.03937,float(TXT[i+2])*0.03937))
f.close()


